# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
# As long as we are in the development stage warnings are not considered errors
warnings_are_errors: false
before_deploy: Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true